### PR TITLE
Allow a global prefix for config field names

### PR DESCRIPTION
**Pull request by ghost**
Hi Jeremy,
I like your config package a lot, minimalist and still covers 99% of the config use cases.

One thing I am missing is using a global prefix for field names. I deploy to k8s and in our environment, a large number of env vars are automatically injected into containers. It is very helpful therefore, to prefix env vars for instance with the app name. Also, with a prefix there is no risk using a prexisting (injected) name. Example:
```
MYAPP__DATABASE_PORT=5432
```

Would be used like
```
var c MyConfig
err := WithPrefix("MYAPP").From("config").FromEnv().To(&c)
```

Added "WithPrefix" funcs and a test for that.

Best regards, Chris

### CODE REVIEW

**Comment by JeremyLoy** [comment]
HI @cbndr, sorry for the late reply. I did not get an email for some reason. I'll check my settings.

https://github.com/JeremyLoy/config/blob/d0690eaabf1ae8a3c57719399b0dbfdfce8be5f2/example_test.go#L30

Does the above not fit your use case already? If not I'll consider adding another method

**Comment by ghost** [comment]
No worries =)
So you are suggesting to encase all config with a struct carrying the name of the app as a work-around?
TBH I'd prefer having a few LOCs for the prefix, as it is also more expressive when reading the code.

**Comment by JeremyLoy** [comment]
@cbndr I see your point now, I agree there would be a lot of benefit here.

What do you think about having a different `To` method? I would like to only parse config into memory a single time. So something like this.

```go
builder := config.FromEnv()
configA := builder.ToOverload(&a, "prefixA")
configB := builder.ToOverload(&b, "prefixB")
```

**Comment by ghost** [comment]
Sure, that could work as well. Although I think the method name "ToOverload" is very self-explanatory. On top of that, From() could accept an additional variadic param to allow for an optional prefix.

**Comment by JeremyLoy** [comment]
Oh haha I didn’t literally mean `ToOverload` , just wanted to make it clear what it was

I don’t want to mess with `From`, since that is doing all the parsing. What about adding the variadic arg to `To`?

**Comment by JeremyLoy** [comment]
Added in v1.4.0!

**Pull request closed without merging**
